DROP TABLE IF EXISTS Web_User CASCADE;
DROP TABLE IF EXISTS Host CASCADE;
DROP TABLE IF EXISTS Attendee CASCADE;
DROP TABLE IF EXISTS Calendar CASCADE;
DROP TABLE IF EXISTS Create_Schedule CASCADE;
DROP TABLE IF EXISTS Vote CASCADE;

CREATE TABLE Web_User (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50),
    password VARCHAR(50)
);

CREATE TABLE Host (
    id SERIAL PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES Web_User(id) ON DELETE CASCADE
);

CREATE TABLE Attendee (
    id SERIAL PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES Web_User(id) ON DELETE CASCADE
);

CREATE TABLE Calendar (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50),
    period TSRANGE
);

CREATE TABLE Create_Schedule (
    hostID INTEGER,
    calendarID INTEGER,
    PRIMARY KEY (hostID, calendarID),
    FOREIGN KEY (hostID) REFERENCES Host(id) ON DELETE CASCADE,
    FOREIGN KEY (calendarID) REFERENCES Calendar(id) ON DELETE CASCADE,
    time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Vote (
    attendeeID INTEGER,
    calendarID INTEGER,
    PRIMARY KEY (attendeeID, calendarID),
    FOREIGN KEY (attendeeID) REFERENCES Attendee(id) ON DELETE CASCADE,
    FOREIGN KEY (calendarID) REFERENCES Calendar(id) ON DELETE CASCADE
);

